# Generated by Django 4.2.7 on 2024-08-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_entrada_bolsas'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='bolsas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
